### ISSUE TITLE
fails to build against newer miniupnpc, but fixed in following bitcoin patch

### ISSUE THREAD

**Issue by 23skdu** [MazaCoin/MazaCoin#13]
Please pull in the following patch from upstream,
to solve compilation issues on more recent versions of miniupnpc.
Thanks!
https://github.com/bitcoin/bitcoin/commit/9f3e48e5219a09b5ddfd6883d1f0498910eff4b6.patch

**Comment by guruvan** [comment]
please build from https://github.com/mazacoin/maza 

This repo is officially deprecated 0.9 series code

0.10 series code has it's own repo as it's a fresh fork from upstream bitcoin

This repo is older zetacoin derived code. You should upgrade  to the latest version
