### ISSUE TITLE
Dependency Issues in Debian instructions

### ISSUE THREAD

**Issue by morpheusbeing** [MazaCoin/MazaCoin#3]
I would also like to point out a couple of other issues:
- Debian is incorrectly spelt - it should be Debian not Debain
- there is something missing at the end of the ntp line 
- instead of using ntp, suggest replacing with apt-get install [dependencies list]
  I am just sorting the dependencies now, but will have to wait, as I am in the middle of an os update from Debian Wheezy to Debian Jessie.

**Comment by boxxa** [comment]
We just posted the dependencies for us to run our test builds the community has asked for. Commited readme changes and spaced out dependencies

**Comment by boxxa** [comment]
Did this build for you too for Deb 6?
